export const GET_ALL_FORCAST_REQUEST = "GET_ALL_FORCAST_REQUEST";
export const GET_ALL_FORCAST_SUCCEED = "GET_ALL_FORCAST_SUCCEED";
export const GET_ALL_FORCAST_FAILED = "GET_ALL_FORCAST_FAILIED";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
